# Modified from BeamBending https://raw.githubusercontent.com/alfredocarella/simplebendingpractice/master/.travis.yml
# ----------------------------------------------------------------------------------------------------------------------
#Main reference for codecoverage addition https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci

# ref: https://docs.travis-ci.com/user/languages/python/
dist: xenial   # required for Python >= 3.7
services:
  - xvfb
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# ref: https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
branches:
  only:
  - main

install:
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install .

# command to test examples and then run tests
script:
  - pytest --cov=indeterminatebeam .tests/

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
