# Modified from BeamBending https://raw.githubusercontent.com/alfredocarella/simplebendingpractice/master/.travis.yml
# ----------------------------------------------------------------------------------------------------------------------

# ref: https://docs.travis-ci.com/user/languages/python/
dist: xenial   # required for Python >= 3.7
services:
  - xvfb
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

# ref: https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
branches:
  only:
  - main

install:
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install .

# command to test examples and then run tests
script:
  # run tests
  - pytest --cov=./

# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov